### DISCUSSION TITLE
EP3246/70 - Abnormal behaviour with D1 Mini - Cancels, won't let coffee run, etc.

### DISCUSSION THREAD

**Discussion by Matze89x** [TillFleisch/ESPHome-Philips-Smart-Coffee#101] [Q&A]
Hello to you and thanks again for the detailed information. I love being able to control my devices locally and get information from them. Thank you very much! :-)

I own an EP3246/70, have it with a D1 Mini and a MOSFET IRLZ44N. Connected as in the picture in the readme of the D1 mini.
Unfortunately I am a real noob when it comes to hardware/soldering! In any case, I got my way and totally misjudged when removing the plug from the control board and ended up with a socket in my hand... with torn parts... embarrassing... - 
In any case, I was able to restore the 4 contacts GND + 5V + TX and RX with ‘light soldering skills’... but unfortunately not the others.

First I tested it without ESP and then with... Unfortunately I get totally different results... 
- Without, the machine runs again as usual and without problems
- With the ESP connected, I can no longer make coffee, the display goes on... It also restarts perfectly, but when making coffee, it simply stops or only runs the rinse very briefly when I switch it on... If I select a coffee manually on the machine, it just starts on its own and, as I said, cancels before it starts...
What have I done wrong?...

As I said, the setup is exactly the same and the connections have been checked several times. I have also set up the following setup in ESPHOME:

```
esphome:
  name: philips-3200-d1-mini
  friendly_name: Philips 3200 D1 mini

#esp8266:
#  board: esp01_1m

# Enable logging
#logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KxcKr2gWyGooDO3tL1OX69oeaOXRtKCG/wMSGG4d4kc="

ota:
  - platform: esphome
    password: "6be9182ae4d2e49fc686cd3c174100c2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Philips-3200-D1-Mini"
    password: "tnURD1uVGGnw"

captive_portal:

esp8266:
  board: d1_mini

# Enable logging
logger:
  # Disable serial logging
  baud_rate: 0

external_components:
  - source: github://TillFleisch/ESPHome-Philips-Smart-Coffee@main

uart:
  # UART connected to the mainboard
  - tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 115200
    id: uart_mainboard

  # UART connected to the display
  - tx_pin: GPIO15
    rx_pin: GPIO13
    baud_rate: 115200
    id: uart_display

philips_coffee_machine:
  display_uart: uart_display
  mainboard_uart: uart_mainboard
  power_pin: GPIO12
  language: de-DE
  model: EP_3246
  read_only: true
  id: philip

text_sensor:
  - platform: philips_coffee_machine
    controller_id: philip
    id: status
    name: "Status"

switch:
  - platform: philips_coffee_machine
    controller_id: philip
    name: "Einschalter"
    clean: false
    icon: mdi:coffee-maker

  - platform: philips_coffee_machine
    controller_id: philip
    name: "Reinigung + Einschalter"
    icon: mdi:coffee-maker
    clean: true

button:
  - platform: philips_coffee_machine
    controller_id: philip
    action: MAKE_COFFEE
    name: "Starte Kaffee"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philip
    action: SELECT_COFFEE
    name: "Kaffee"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philip
    action: PLAY_PAUSE
    name: "Start/Stop"

number:
  - platform: philips_coffee_machine
    type: bean
    name: "Aromastärke"
    controller_id: philip
    status_sensor_id: status

  - platform: philips_coffee_machine
    type: size
    name: "Trinkmenge"
    controller_id: philip
    status_sensor_id: status
```

I probably made such a simple mistake and I'm just blind... I hope you can help me.

Thank you very much.

**Comment by Matze89x** [comment]
So that I can now make myself a coffee normally again (I couldn't... always started by itself when selecting ‘coffee’ and choosing bean/quantity and then cancelled completely after grinding the beans (as if the ESP was constantly sending a start/stop by itself)...

Now I have done the following:

TX mainboard + TX display + TX on ESP for display + TX on ESP for mainboard
and
RX mainboard + RX display + RX on ESP for display + RX on ESP for mainboard completely bridged.... so it reads along but unfortunately can no longer send anything...

as I said, I'm really at a loss... I can also make a video + provide debug logs (but it's a hell of a lot of what it sends per second...)

![image](https://github.com/user-attachments/assets/d14219f7-b661-414e-902b-757fcd6bb04e)
![image](https://github.com/user-attachments/assets/e6150efb-8908-44ef-b9fd-796dcff1db76)

**Comment by Matze89x** [comment]
I keep trying to find out what the problem is... I even bought a new esp board and soldered everything neatly onto the board from @SchmDan (thanks again)...
Exactly the same symptoms. It permanently controls the machine independently with different commands without doing anything... simply cancels coffee making at the start and sends commands from the ESP independently, which should not happen.

Had to bridge the two TX+RX again so that I can operate the machine normally again....

I have generated a complete log here incl. TXT file of the log. I ask for your help.

What else could I output? Should I also output a debug from the mainboard?


[logs_coffeepcb_run.txt](https://github.com/user-attachments/files/20759893/logs_coffeepcb_run.txt)

**Reply by quack3d** [reply]
I had lots of erratic behaviour when I used an ESP8266. When I switched to ESP32 S2 Mini it worked fine. Another user reported the same. 

Picture of my wiring here: https://github.com/quack3d/ESPHome-Philips-Smart-Coffee-3200-Series

**Comment by Matze89x** [comment]
Hello @quack3d
I would like to thank you very much for your advice. I have now ordered an S2 mini and hope for fast delivery... I will test it immediately and report back :-)

So it definitely couldn't be a software problem? I don't understand why the machine does what it wants and receives commands that nobody has pressed...

**Comment by quack3d** [comment]
I'm sure it could be a software problem as well but the owner of this repo uses a 2200 series machine. A few of us with 3200 series had issues like you describe and just needed to change to the ESP32 S2 Mini.

**Reply by Matze89x** [reply]
oh before I forget to ask again. Should I get it from your extermal_components or from TillFleisch? Unfortunately I don't know how the code has changed recently. Change the code so far?

```
esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

external_components:
  - source: github://TillFleisch/ESPHome-Philips-Smart-Coffee@main

uart:
  # UART connected to the mainboard
  - tx_pin: GPIO39
    rx_pin: GPIO37   
    baud_rate: 115200
    id: uart_mainboard

  # UART connected to the display
  - tx_pin: GPIO17
    rx_pin: GPIO21  
    baud_rate: 115200
    id: uart_display   
```

**Comment by quack3d** [comment]
I suggest you use the GPIOs I used but for the external_component choose TillFleisch. My repo is deprecated. Here is my setup with a couple of extra counters:

```
esphome:
  name: "esp32-kaffemaskin"
  friendly_name: ESP32 Kaffemaskin

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

# Enable logging
logger:
  # Disable serial logging
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: "asflkjafhlakjfhaskjlf235235lkjsflkjs"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 10.0.0.56
    gateway: 10.0.0.1
    subnet: 255.255.255.0 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Kaffemaskin"
    password: "kjahsdi9y234jklahf"

captive_portal:

external_components:
 - source: github://TillFleisch/ESPHome-Philips-Smart-Coffee@main

uart:
  # UART connected to the mainboard
  - tx_pin: GPIO39
    rx_pin: GPIO37   
    baud_rate: 115200
    id: uart_mainboard  

  # UART connected to the display
  - tx_pin: GPIO17
    rx_pin: GPIO21  
    baud_rate: 115200
    id: uart_display   

philips_coffee_machine:
  display_uart: uart_display
  mainboard_uart: uart_mainboard
  power_pin: GPIO35
  id: philips
  model: EP_3243

globals:
  - id: service_interval_counter
    type: int
    restore_value: true
    #initial_value: '0'
  - id: brew_count
    type: int
    restore_value: true
    #initial_value: '0'  

text_sensor:
  - platform: philips_coffee_machine
    controller_id: philips
    id: status
    name: "Status"
    on_value:
      then:
        - lambda: |-
            if (id(status).state.find("Brewing 2x") != std::string::npos) {
              id(brew_count) += 2;
              id(service_interval_counter) += 2;
            } else if (id(status).state.find("Brewing") != std::string::npos) {
              id(brew_count) += 1;
              id(service_interval_counter) += 1;
            }       

switch:
  - platform: philips_coffee_machine
    controller_id: philips
    name: "Power With Clean"
    icon: mdi:coffee-maker
    clean: true

  - platform: philips_coffee_machine
    controller_id: philips
    name: "Power Without Clean"
    icon: mdi:coffee-maker
    clean: false      

button:
  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_COFFEE
    name: "Select Coffee"
    icon: mdi:coffee    

  - platform: philips_coffee_machine
    controller_id: philips
    action: BEAN
    name: "Select Ground Coffee"
    icon: mdi:coffee   
    long_press: true

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_ESPRESSO
    name: "Select Espresso"
    icon: mdi:coffee 

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_HOT_WATER
    name: "Select Hot water"
    icon: mdi:tea

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_LATTE
    name: "Select Latte Macchiato"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_AMERICANO
    name: "Select Americano"
    icon: mdi:coffee    

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_CAPPUCCINO
    name: "Select Cappuccino"
    icon: mdi:coffee 

  - platform: philips_coffee_machine
    controller_id: philips
    action: PLAY_PAUSE
    name: "Select play/pause"
    icon: mdi:play-pause

  - platform: template
    name: "Reset Service Interval Counter"
    on_press:
      then:
        - lambda: |-
            id(service_interval_counter) = 0;

  - platform: template
    name: "Reset Brew Count"
    on_press:
      then:
        - lambda: |-
            id(brew_count) = 0;

number:
  - platform: philips_coffee_machine
    type: size
    name: "Size"
    controller_id: philips
    status_sensor_id: status 

  - platform: philips_coffee_machine
    type: bean
    name: "Strength"
    controller_id: philips
    status_sensor_id: status 

  - platform: philips_coffee_machine
    type: milk
    name: "Milk"
    controller_id: philips
    status_sensor_id: status 

sensor:
  - platform: template
    name: "Service Interval Counter"
    lambda: |-
      return id(service_interval_counter);
    state_class: measurement
    unit_of_measurement: "count"
    accuracy_decimals: 0

  - platform: template
    name: "Brew Count"
    lambda: |-
      return id(brew_count);
    state_class: measurement
    unit_of_measurement: "count"
    accuracy_decimals: 0            
```

**Comment by Matze89x** [comment]
hey @quack3d

 I have it in front of me! :-)
Now I want to ask you/you one more thing quickly... I could use the CoffePCB, couldn't I? I would then only have to change the GPIO pins but in principle I could use the same as the D1 Mini before? or am I wrong?

Everything fits on the right... but on the left I would now only have to use gpio 11 and 12 and GPIO 16 for the GND bridges?

**Reply by quack3d** [reply]
Sorry, not sure.

**Comment by Matze89x** [comment]
I would like to thank you very much for this brilliant advice with the S2 Mini. It was actually the ESP D1... I would never have believed that after several attempts!

But I definitely need to tell you/you about another incredible obstacle course regarding the ESP S2 Mini and let others know about it! - I received 3 of them and none of them booted up continuously after flashing (some rebooted again and again after 2 minutes or less), could not withstand WLAN and lost the connection continuously... Even asking ChatGPT didn't bring any useful result...

Then I found this important information on Google:
https://forum.arduino.cc/t/esp32-s2-wemos-s2-mini-powering-issues-5v-vbus-pin/1166260/5
(PS: I also ordered them from Amazon with today's delivery... - such a sh....)

I had no idea before and am not that deep into the subject. I then carefully scratched and soldered... Voila... it works...

Next stage, unfortunately I had to move away from the CoffeePCB board because the left pin side had to be kept free for other functions... So I flipped everything over again and soldered it on the right, exactly according to your instructions and setup. What I have currently dispensed with are the 320 ohms on the IRFZ44N mosfet.

Here I provide my Germanised version for other 3200 owners. The statistics are brilliant. 

Thanks again, I can finally use the machine remotely and physically on the touch panel. :-) That's great!

![image](https://github.com/user-attachments/assets/bda58ae4-3cf8-4bd3-b488-b7385b92ded7)

My YAML:
```
esphome:
  name: philipscoffee
  friendly_name: PhilipsCoffee

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

# Enable logging
logger:
  # Disable serial logging
  baud_rate: 0

external_components:
  - source: github://TillFleisch/ESPHome-Philips-Smart-Coffee@main

# Enable Home Assistant API
api:
  encryption:
    key: "XXXX"

ota:
  - platform: esphome
    password: "XXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Philipscoffee Fallback Hotspot"
    password: "XXXX"

uart:
  # UART connected to the mainboard
  - tx_pin: GPIO39
    rx_pin: GPIO37   
    baud_rate: 115200
    id: uart_mainboard  

  # UART connected to the display
  - tx_pin: GPIO17
    rx_pin: GPIO21  
    baud_rate: 115200
    id: uart_display   

philips_coffee_machine:
  display_uart: uart_display
  mainboard_uart: uart_mainboard
  power_pin: GPIO35
  id: philips
  model: EP_3243
  language: de-DE
globals:
  - id: service_interval_counter
    type: int
    restore_value: true
    #initial_value: '0'
  - id: brew_count
    type: int
    restore_value: true
    #initial_value: '0'  

text_sensor:
  - platform: philips_coffee_machine
    controller_id: philips
    id: status
    name: "Status"
    on_value:
      then:
        - lambda: |-
            if (id(status).state.find("Bereitet 2x") != std::string::npos) {
              id(brew_count) += 2;
              id(service_interval_counter) += 2;
            } else if (id(status).state.find("Bereitet") != std::string::npos) {
              id(brew_count) += 1;
              id(service_interval_counter) += 1;
            }       

switch:  
  - platform: philips_coffee_machine
    controller_id: philips
    name: "Einschalter"
    clean: false
    icon: mdi:coffee-maker

  - platform: philips_coffee_machine
    controller_id: philips
    name: "Reinigung + Einschalter"
    icon: mdi:coffee-maker
    clean: true

button:
  - platform: philips_coffee_machine
    controller_id: philips
    action: PLAY_PAUSE
    name: "Start/Stop"
    icon: mdi:play-pause

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_COFFEE
    name: "Kaffee"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_ESPRESSO
    name: "Espresso"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_AMERICANO
    name: "Americano"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_CAPPUCCINO
    name: "Cappuccino"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_LATTE
    name: "Latte Macchiato"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: SELECT_HOT_WATER
    name: "Heißwasser"
    icon: mdi:tea


  - platform: philips_coffee_machine
    controller_id: philips
    action: MAKE_COFFEE
    name: "Starte Kaffee"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: MAKE_ESPRESSO
    name: "Starte Espresso"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: MAKE_AMERICANO
    name: "Starte Americano"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: MAKE_CAPPUCCINO
    name: "Starte Cappuccino"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: MAKE_LATTE
    name: "Starte Latte Macchiato"
    icon: mdi:coffee

  - platform: philips_coffee_machine
    controller_id: philips
    action: MAKE_HOT_WATER
    name: "Starte Heißwasser"
    icon: mdi:tea

  - platform: template
    name: "Service-Zähler zurücksetzen"
    on_press:
      then:
        - lambda: |-
            id(service_interval_counter) = 0;

  - platform: template
    name: "Brühzahl zurücksetzen"
    on_press:
      then:
        - lambda: |-
            id(brew_count) = 0;

number:
  - platform: philips_coffee_machine
    type: bean
    name: "Aromastärke"
    controller_id: philips
    status_sensor_id: status

  - platform: philips_coffee_machine
    type: size
    name: "Trinkmenge"
    controller_id: philips
    status_sensor_id: status

  - platform: philips_coffee_machine
    type: milk
    name: "Milchmenge"
    controller_id: philips
    status_sensor_id: status

sensor:
  - platform: template
    name: "Service-Zähler"
    lambda: |-
      return id(service_interval_counter);
    state_class: measurement
    unit_of_measurement: "mal"
    accuracy_decimals: 0

  - platform: template
    name: "Anzahl Brühungen"
    lambda: |-
      return id(brew_count);
    state_class: measurement
    unit_of_measurement: "mal"
    accuracy_decimals: 0     
```
