### DISCUSSION TITLE
Disable auto clean after power on

### DISCUSSION THREAD

**Discussion by djacid** [TillFleisch/ESPHome-Philips-Smart-Coffee#53] [Q&A] [answered]
Hello, as I can see on reddit, you said that it's possible to disable auto clean after startup. Could you tell me how to achieve this?

**Comment by TillFleisch** [comment, marked as answer]
> - **clean**(**Optional**: boolean): If set to `true` the machine will perform a cleaning cycle during startup. Otherwise the machine will power on without cleaning. Defaults to `true`.

Cleaning is an option on the Power switch. You can find more details in the [readme](https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee?tab=readme-ov-file#philips-power-switch). You may use a configuration like this to achieve your goal.

```yaml
  - platform: philips_power_switch
    controller_id: philip
    clean: false
    id: power_without_cleaning
    name: "Power without cleaning"
    icon: mdi:coffee-maker
```
