### ISSUE TITLE
Sensor for Bean/Coffee Size

### ISSUE THREAD

**Issue by Joshi425** [TillFleisch/ESPHome-Philips-Smart-Coffee#12]
Hello,

nice work with this component, works like a Charm 👌 
I was wondering if there is an easy way to access the currently selected Bean/Coffee Size. At the moment I only see the Text Status Sensor.

When the mosfet resets the display Unit on my Maschine sometimes the settings for Bean/Coffee Size reset to 2/2. For A fully automated 
Coffee it would be great to have those as a sensor to make the Coffee like I want. It looks like its also already decoded 

https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/blob/main/protocol.md#messages-from-the-display-to-the-mainboard-1

so should be trivial to implemet right?

thanks for your great Work.

Joshi

**Comment by TillFleisch** [comment]
@Joshi425 can check out/give feedback on the new feature by adding the following to your configuration:

```yaml
external_components:
  - source: github://TillFleisch/ESPHome-Philips-Smart-Coffee@bean_and_water_sensor

number:
  - platform: philips_bean_settings
    name: "Coffee beans"
    controller_id: philip
    status_sensor_id: status
    source: COFFEE

  - platform: philips_size_settings
    name: "Coffee size"
    controller_id: philip
    status_sensor_id: status
    source: COFFEE
```
