### ISSUE TITLE
Having issues using esphome  2023.3.2 and example.yaml

### ISSUE THREAD

**Issue by schlunsen** [TillFleisch/ESPHome-Philips-Smart-Coffee#2]
First of all - really nice project and thanks for publishing the code!

I think the current example.yaml isn't up to date with newest version of esphome.

What version of esphome are you currently using?

I'm trying to run `esphome run example.yaml`, but getting the following errors
```
display_uart: uart_display
  mainboard_uart: uart_mainboard
  power_pin: GPIO12
  id: philip
text_sensor.philips_status_sensor: [source example.yaml:43]

  Platform not found: 'text_sensor.philips_status_sensor'.
  platform: philips_status_sensor
  controller_id: philip
  name: Status
switch.philips_power_switch: [source example.yaml:48]

  Platform not found: 'switch.philips_power_switch'.
  platform: philips_power_switch
  controller_id: philip
  name: Power
  icon: mdi:coffee-maker
```

**Comment by TillFleisch** [comment]
I updated to 2023.3.2, and my .yaml file compiled successfully.

After adding
```
esphome:
  name: example
  friendly_name: example
```
to the [example.yaml](https://github.com/TillFleisch/ESPHome-Philips-Smart-Coffee/blob/6602c047c5be34efb0a6ec42af0bb32b5c4a3d49/example.yaml), it also compiled successfully.

It looks like your configuration cannot find the custom component.
Make sure you add the component by adding the `external component` section to your yaml like this:
```
external_components:
  - source: github://TillFleisch/ESPHome-Philips-Smart-Coffee@main
```

If you are using a local copy of the repository, ensure the selected path is correct.

**Comment by schlunsen** [comment]
Still having issues even when using github as external source.

Will look into it later this week, but I do see the components being downloaded to the .esphome/external_components


My example.yaml

```
esphome:
  name: example
  friendly_name: example

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  # Disable serial logging
  baud_rate: 0

external_components:
  - source: github://TillFleisch/ESPHome-Philips-Smart-Coffee@main


uart:
  # UART connected to the mainboard
  - tx_pin: GPIO1
    rx_pin: GPIO3
    baud_rate: 115200
    id: uart_mainboard

  # UART connected to the display
  - tx_pin: GPIO14
    rx_pin: GPIO13
    baud_rate: 115200
    id: uart_display

philips_series_2200:
  display_uart: uart_display
  mainboard_uart: uart_mainboard
  power_pin: GPIO12
  id: philip

text_sensor:
  - platform: philips_status_sensor
    controller_id: philip
    name: "Status"

switch:
  - platform: philips_power_switch
    controller_id: philip
    name: "Power"
    icon: mdi:coffee-maker
```


And still with the same error messages:

```
Failed config

philips_series_2200: [source example.yaml:33]

  Component not found: philips_series_2200.
  display_uart: uart_display
  mainboard_uart: uart_mainboard
  power_pin: GPIO12
  id: philip
text_sensor.philips_status_sensor: [source example.yaml:39]

  Platform not found: 'text_sensor.philips_status_sensor'.
  platform: philips_status_sensor
  controller_id: philip
  name: Status
switch.philips_power_switch: [source example.yaml:44]

  Platform not found: 'switch.philips_power_switch'.
  platform: philips_power_switch
  controller_id: philip
  name: Power
  icon: mdi:coffee-maker
```
