### ISSUE TITLE
cant add restart button

### ISSUE THREAD

**Issue by b2un0** [TillFleisch/ESPHome-Philips-Smart-Coffee#96]
if i add this to my yaml

```yaml

button:
  - platform: restart
    name: "restart"
    entity_category: diagnostic
```

i got this error:

```
NFO ESPHome 2025.2.1
INFO Reading configuration /config/coffeemaker.yaml...
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.5.1
INFO Compiling app...
Processing coffeemaker (board: esp32-c3-devkitm-1; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32.git#51.03.07)
--------------------------------------------------------------------------------
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.50105.0 (5.1.5) 
 - tool-cmake @ 3.21.3 
 - tool-esptoolpy @ 4.8.1 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.7.1 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 12.2.0+20230208
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.6
Compiling .pioenvs/coffeemaker/src/esphome/components/philips_coffee_machine/philips_coffee_machine.cpp.o
Compiling .pioenvs/coffeemaker/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/coffeemaker/src/esphome/components/sensor/filter.cpp.o
Compiling .pioenvs/coffeemaker/src/esphome/components/sensor/sensor.cpp.o
In file included from src/esphome/components/philips_coffee_machine/philips_coffee_machine.cpp:2:
src/esphome/components/philips_coffee_machine/philips_coffee_machine.h:10:10: fatal error: button/action_button.h: No such file or directory
   10 | #include "button/action_button.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/coffeemaker/src/esphome/components/philips_coffee_machine/philips_coffee_machine.cpp.o] Error 1
```

## full yaml

```yaml
substitutions:
  name: "coffeemaker"
  comment: "Philips EP3246 (ESP32-C3)"

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    
esphome:
  name: $name
  comment: $comment
  friendly_name: $name
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB

api:
  encryption:
    key: !secret api_encryption

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "$name Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

external_components:
  - source: github://TillFleisch/ESPHome-Philips-Smart-Coffee@main

logger:
  level: DEBUG
  baud_rate: 0
  logs:
    component: ERROR

uart:
  # UART connected to the mainboard
  - tx_pin: GPIO21
    rx_pin: GPIO20
    baud_rate: 115200
    id: uart_mainboard
      
  # UART connected to the display
  - tx_pin: GPIO5
    rx_pin: GPIO6
    baud_rate: 115200
    id: uart_display

philips_coffee_machine:
  display_uart: uart_display
  mainboard_uart: uart_mainboard
  power_pin: GPIO0
  id: philip
  model: EP_3246

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic

text_sensor:
  - platform: philips_coffee_machine
    controller_id: philip
    id: status
    name: "Status"

  - platform: uptime
    name: Uptime
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      id: wifi_ip
      name: "IP Address"
      entity_category: diagnostic

button:
  - platform: restart
    name: "restart"
    entity_category: diagnostic

switch:
  - platform: philips_coffee_machine
    controller_id: philip
    name: "Power"
    icon: mdi:coffee-maker
    clean: true

  - platform: philips_coffee_machine
    controller_id: philip
    name: "Power (no clean)"
    icon: mdi:coffee-maker
    clean: false

  - platform: safe_mode
    name: "restart (Safe Mode)"
    entity_category: diagnostic
```
